pr:
  autoCancel: true
  branches:
    exclude:
      - master

name: $(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

variables:
  - group: Tokens
  
workspace:
    clean: all

jobs:
- job: ubuntu
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
    - task: UseDotNet@2
      displayName: 'Install .NET Core SDK'
      inputs:
        packageType: sdk
        version: 2.2.401
        installationPath: $(Agent.ToolsDirectory)/dotnet
    - bash: ./build.sh -target=Tests
      displayName: 'Tests on Ubuntu'
- job: macos
  pool:
    vmImage: 'macOS-10.14'
  steps:
    - task: UseDotNet@2
      displayName: 'Install .NET Core SDK'
      inputs:
        packageType: sdk
        version: 2.2.401
        installationPath: $(Agent.ToolsDirectory)/dotnet
    - bash: ./build.sh -target=Tests
      displayName: 'Tests on MacOS'