trigger:
  - refs/tags/*

name: $(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

pool:
  vmImage: ubuntu-16.04

variables:
  - group: Tokens

steps:
  - task: UseDotNet@2
    displayName: "Use .Net Core SDK global.json"
    inputs:
      useGlobalJson: true
  - task: UseDotNet@2
    displayName: "Use .Net Core SDK 2.1.801"
    inputs:
      version: 2.1.801
  - bash: ./build.sh -target=sonar
    env:
      Sonar_Token: $(Sonar_Token)
      Version: $(Build.SourceBranchName)
    displayName: Sonar Build
  - bash: ./build.sh -target=publish
    env:
      Version: $(Build.SourceBranchName)
    displayName: Create Artifacts
  - bash: ./build.sh -target=push
    env:
      Nuget_Token: $(Nuget_Token)
    displayName: Publish Packages
