name: Release

on:
  push:
    tags:
      - "*"

jobs:
  tests:
    uses: ./.github/workflows/test-matrix.yml
    with:
      include_docker_info: false
  release:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use .NET SDK from global.json
        uses: actions/setup-dotnet@v4
      - name: Build, Test and Push
        uses: swisslife-oss/actions/release-packages@main
        with:
          tag: ${{ github.ref_name }}
          nuget_api_key: ${{ secrets.NUGET_API_KEY }}
          enable_push: 'yes'
